### ISSUE TITLE
Feature Request: Readme

### ISSUE THREAD

**Issue by cboseak** [yongye/cpp#1]
Update readme to note:

c++11 is required. 

A cross compiler is needed.... compiling on windows g++ gives error "termios.h no such file or directory"

**Comment by yongye** [comment]
It's Linux platform oriented only!

**Comment by cboseak** [comment]
Ah that makes sense. I'll close the ticket.  


-------- Original message --------

**Comment by cboseak** [comment]
will fork and make win version.
